version: "3.0"

services:
  postgres:
    container_name: postgres
    image: postgres:16
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

  main:
    container_name: main
    build:
      context: .
    env_file:
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "7654:7654"
      - "9229:9229"
    command: npm run start:dev
    depends_on:
      - postgres
    restart: always


volumes:
  postgres: