version: "3.0"

services:
  postgres:
    container_name: postgres
    image: postgres:16
    environment:
      POSTGRES_DB: english-reporting
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379"
    restart: always
    networks:
      - app-network

  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "7654:7654"
      - "9229:9229"
    command: sh -c "npx prisma db push && npm run start:dev"
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - main
    restart: always
    networks:
      - app-network


volumes:
  postgres:

networks:
  app-network: