version: "3.0"
services:
  postgres:
    container_name: postgres
    image: postgres:16
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379"
    restart: always
    networks:
      - app-network

  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "${MAIN_APP_PORT}:7654"
      - "${MAIN_DEBUG_PORT}:9229"
    command: sh -c "npx prisma migrate deploy && npm run start"
    depends_on:
      - postgres
      - redis
    restart: always
    networks:
      - app-network

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - main
      - client
    restart: always
    networks:
      - app-network

volumes:
  postgres:

networks:
  app-network:
